version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vPlBIkOyAQcGdGGZOiEY
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  web:
    build: web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./web/src:/var/www/html # Not needed in production
  bot:
    build: bot
    restart: always
    depends_on: 
      - web
      
  debug-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: vPlBIkOyAQcGdGGZOiEY
